//const of giang vien 
export const GETDANHSACH_LOPHOC_SUCCESS="giangvien/GETDANHSACH_LOPHOC_SUCCESS";
export const GETDANHSACH_LOPHOC_FAILED="giangvien/GETDANHSACH_LOPHOC_FAILED";



export const GETDANHSACH_LOPHOCPHAN_SUCCESS="giangvien/GETDANHSACH_LOPHOCPHAN_SUCCESS";
export const GETDANHSACH_LOPHOCPHAN_FAILED="giangvien/GETDANHSACH_LOPHOCPHAN_FAILED";



export const GETSINHVIENS_LOPHOC_SUCCESS = "giangvien/GETSINHVIENS_LOPHOC_SUCCESS";
export const GETSINHVIENS_LOPHOC_FAILED = "giangvien/GETSINHVIENS_LOPHOC_FAILED";

export const GETSINHVIENS_LOPHOCPHAN_SUCCESS = "giangvien/GETSINHVIENS_LOPHOCPHAN_SUCCESS";
export const GETSINHVIENS_LOPHOCPHAN_FAILED = "giangvien/GETSINHVIENS_LOPHOCPHAN_FAILED";


export const GETDONXINNGHIHOC_SUCCESS = "giangvien/GETDONXINNGHIHOC_SUCCESS";
export const GETDONXINNGHIHOC_FAILED = "giangvien/GETDONXINNGHIHOC_FAILED";


export const GETTHONGBAOSINHVIENS_LOPHOC_SUCCESS = "giangvien/GETTHONGBAOSINHVIENS_LOPHOC_SUCCESS";
export const GETTHONGBAOSINHVIENS_LOPHOC_FAILED = "giangvien/GETTHONGBAOSINHVIENS_LOPHOC_FAILED";

export const GETTHONGBAOSINHVIENS_LOPHOCPHAN_SUCCESS = "giangvien/GETTHONGBAOSINHVIENS_LOPHOCPHAN_SUCCESS";
export const GETTHONGBAOSINHVIENS_LOPHOCPHAN_FAILED = "giangvien/GETTHONGBAOSINHVIENS_LOPHOCPHAN_FAILED";



export const ADDTHONGBAOSINHVIENS_LOPHOC_SUCCESS = "giangvien/ADDTHONGBAOSINHVIENS_LOPHOC_SUCCESS";
export const ADDTHONGBAOSINHVIENS_LOPHOC_FAILED = "giangvien/ADDTHONGBAOSINHVIENS_LOPHOC_FAILED";




export const EDITTHONGBAOSINHVIENS_LOPHOC_SUCCESS = "giangvien/EDITTHONGBAOSINHVIENS_LOPHOC_SUCCESS";
export const EDITTHONGBAOSINHVIENS_LOPHOC_FAILED = "giangvien/EDITTHONGBAOSINHVIENS_LOPHOC_FAILED";

export const EDITDISPLAYTHONGBAOSINHVIENS_LOPHOC_SUCCESS = "giangvien/EDITDISPLAYTHONGBAOSINHVIENS_LOPHOC_SUCCESS";
export const EDITDISPLAYTHONGBAOSINHVIENS_LOPHOC_FAILED = "giangvien/EDITDISPLAYTHONGBAOSINHVIENS_LOPHOC_FAILED";









export const ADDTHONGBAOSINHVIENS_LOPHOCPHAN_SUCCESS = "giangvien/ADDTHONGBAOSINHVIENS_LOPHOCPHAN_SUCCESS";
export const ADDTHONGBAOSINHVIENS_LOPHOCPHAN_FAILED = "giangvien/ADDTHONGBAOSINHVIENS_LOPHOCPHAN_FAILED";




export const EDITTHONGBAOSINHVIENS_LOPHOCPHAN_SUCCESS = "giangvien/EDITTHONGBAOSINHVIENS_LOPHOCPHAN_SUCCESS";
export const EDITTHONGBAOSINHVIENS_LOPHOCPHAN_FAILED = "giangvien/EDITTHONGBAOSINHVIENS_LOPHOCPHAN_FAILED";

export const EDITDISPLAYTHONGBAOSINHVIENS_LOPHOCPHAN_SUCCESS = "giangvien/EDITDISPLAYTHONGBAOSINHVIENS_LOPHOCPHAN_SUCCESS";
export const EDITDISPLAYTHONGBAOSINHVIENS_LOPHOCPHAN_FAILED = "giangvien/EDITDISPLAYTHONGBAOSINHVIENS_LOPHOCPHAN_FAILED";








export const SELECT_0 = "giangvien/SELECT_0";
export const SELECT_1 = "giangvien/SELECT_1";
export const SELECT_2 = "giangvien/SELECT_2";
export const SELECT_3 = "giangvien/SELECT_3";



export const GET_CANHBAO_SINHVIEN_SUCCESS = "giangvien/GET_CANHBAO_SINHVIEN_SUCCESS";
export const GET_CANHBAO_SINHVIEN_FAILED = "giangvien/GET_CANHBAO_SINHVIEN_FAILED";



export const CANHBAO_SINHVIEN_SUCCESS = "giangvien/CANHBAO_SINHVIEN_SUCCESS";
export const CANHBAO_SINHVIEN_FAILED = "giangvien/CANHBAO_SINHVIEN_FAILED";




export const GETNGAYNGHI_SINHVIEN_SUCCESS = "giangvien/GETNGAYNGHI_SINHVIEN_SUCCESS";
export const GETNGAYNGHI_SINHVIEN_FAILED = "giangvien/GETNGAYNGHI_SINHVIEN_FAILED";
