/*
  sinh vien act
*/

export const XEMTHONGTINSINHVIEN_SUCCESS = "sinhvien/XEMTHONGTINSINHVIEN_SUCCESS";
export const XEMTHONGTINSINHVIEN_FAILED = "sinhvien/XEMTHONGTINSINHVIEN_FAILED";

export const CHINHSUATHONGTINSINHVIEN_SUCCESS = "sinhvien/CHINHSUATHONGTINSINHVIEN_SUCCESS";
export const CHINHSUATHONGTINSINHVIEN_FAILED = "sinhvien/CHINHSUATHONGTINSINHVIEN_FAILED";


export const GETTHONGBAOSINHVIEN_SUCCESS  ="sinhvien/GETTHONGBAOSINHVIEN_SUCCESS";
export const GETTHONGBAOSINHVIEN_FAILED  ="sinhvien/GETTHONGBAOSINHVIEN_FAILED";

export const GETDONXINNGHIHOC_OFSINHVIEN_SUCCESS  ="sinhvien/GETDONXINNGHIHOC_OFSINHVIEN_SUCCESS";
export const GETDONXINNGHIHOC_OFSINHVIEN_FAILED  ="sinhvien/GETDONXINNGHIHOC_OFSINHVIEN_FAILED";



export const GETDIEMSINHVIEN_SUCCESS  ="sinhvien/GETDIEMSINHVIEN_SUCCESS";
export const GETDIEMSINHVIEN_FAILED  ="sinhvien/GETDIEMSINHVIEN_FAILED";




export const GETLOPHOCPHANSINHVIEN_SUCCESS  ="sinhvien/GETLOPHOCPHANSINHVIEN_SUCCESS";
export const GETLOPHOCPHANSINHVIEN_FAILED  ="sinhvien/GETLOPHOCPHANSINHVIEN_FAILED";


export const GETDIEMSINHVIEN  ="sinhvien/GETDIEMSINHVIEN";



