/*
đăng nhập
*/
export const DANGNHAP_REQUEST = "taikhoan/DANGNHAP_REQUEST";
export const DANGNHAP_SUCCSESS = "taikhoan/DANGNHAP_SUCCSESS";
export const DANGNHAP_FAILED = "taikhoan/DANGNHAP_FAILED";


export const CHANGEPASSWORD_SUCCSESS = "taikhoan/CHANGEPASSWORD_SUCCSESS";
export const CHANGEPASSWORD_FAILED = "taikhoan/CHANGEPASSWORD_FAILED";



export const CHANGEIMGURL_SUCCSESS = "taikhoan/CHANGEIMGURL_SUCCSESS";
export const CHANGEIMGURL_FAILED = "taikhoan/CHANGEPASSWORD_FAILED";


